### PR TITLE
feat: allow setting root

### PR DESCRIPTION
**Pull request by aminya**
Made on top of #32

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why? What's the use-case?

**Comment by aminya** [comment]
This allows to store all the temp files in a given directory. Another implementation can be introducing a new option like `rootDirectory` which is `path.join`ed to `tempDir`.

https://github.com/atom-community/atom-script/blob/eb8bea2794e4280baf63b053c7688225e0e15fff/lib/grammar-utils.js#L11

**Comment by sindresorhus** [comment]
Why do you need a `rootDirectory` option? Or rather, why do you need to store everything under one named directory? I'm trying to understand what problems it would solve.

**Comment by aminya** [comment]
Because I want to keep everything related to my software under a folder nice and clean so I can later check for its existence, or I can remove easily using `rimraf`.

I ended up using `node-temp` which allows setting `dir` in its options.
https://github.com/bruce/node-temp#affixes

**Pull request closed without merging**
